{% set name = "nceplibs-sp" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NOAA-EMC/NCEPLIBS-sp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: aec475ccb5ccf7c5a758dfb699626f2be78a22729a9d8d5e0a286db6a3213a51

build:
  number: 5

requirements:
  build:
    - {{ compiler("fortran") }}
    - {{ stdlib("c") }}     # [not win]
    - m2w64-gcc-fortran           # [win]
    - cmake
    - pkg-config >=0.21
    - make                  # [not win]
    - ninja                 # [win]
  host:
    - llvm-openmp
    - m2w64-gcc-fortran           # [win]
  run:
    - m2w64-gcc-libs              # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libsp_4${SHLIB_EXT} -a -f ${PREFIX}/lib/libsp_d${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_BIN%\\libsp_4.dll exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\libsp_d.dll exit 1  # [win]

about:
  home: https://github.com/NOAA-EMC/NCEPLIBS-sp
  summary: The spectral transform library (splib) contains FORTRAN subprograms to be used for a variety of spectral transform functions.
  license: LGPL-3.0-only
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - EricEngle-NOAA
    - TimothyCera-NOAA
